```yaml
name: Documentation

on:
  push:
    branches:
      - master  # Your main branch

jobs:
  docs:

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'  # Specify your Julia version

      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'

      - name: Build the documentation
        run: julia --project=docs docs/make.jl

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for pushing to gh-pages
          publish_dir: docs/build
